Creating Numpy Arrays

In [1]:
list_1 = [1, 2, 3]
print(list_1)

[1, 2, 3]


In [2]:
import numpy as np

In [4]:
numpy_1 = np.array(list_1)

In [8]:
print(numpy_1)

[1 2 3]


In [12]:
zeros_array = np.zeros(10)
print(zeros_array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [16]:
ones_array = np.ones(10)
print(ones_array)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


Make Range Array

In [21]:
range_array = np.arange(1, 5)
print(range_array)

[1 2 3 4]


In [23]:
range_array_2 = np.arange(11)
print(range_array_2)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [31]:
range_array_3 = np.arange(0, 21, 2)
print(range_array_3)

[ 0  2  4  6  8 10 12 14 16 18 20]


form ==> np.linspace(<min num>, <max num>, <number of number between min to max num>

In [35]:
linspace_array = np.linspace(0, 100, 5)
print(linspace_array)

[  0.  25.  50.  75. 100.]


If we not spicify the third parameter, he will be 50 elements

In [40]:
linspace_array_1 = np.linspace(0, 500)
print("Total Elements",len(linspace_array_1), sep=": ")
print(linspace_array_1)

Total Elements: 50
[  0.          10.20408163  20.40816327  30.6122449   40.81632653
  51.02040816  61.2244898   71.42857143  81.63265306  91.83673469
 102.04081633 112.24489796 122.44897959 132.65306122 142.85714286
 153.06122449 163.26530612 173.46938776 183.67346939 193.87755102
 204.08163265 214.28571429 224.48979592 234.69387755 244.89795918
 255.10204082 265.30612245 275.51020408 285.71428571 295.91836735
 306.12244898 316.32653061 326.53061224 336.73469388 346.93877551
 357.14285714 367.34693878 377.55102041 387.75510204 397.95918367
 408.16326531 418.36734694 428.57142857 438.7755102  448.97959184
 459.18367347 469.3877551  479.59183673 489.79591837 500.        ]
