Operations to get elements or properties of an array

In [6]:
import numpy as np

In [16]:
an_array = np.arange(0, 11)
print(an_array)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [17]:
first = an_array[0]
last = an_array[len(an_array)-1]
print("First", first, sep=": ")
print("Last", last, sep=": ")

First: 0
Last: 10


Acces Multiple Elements

In [21]:
first_five = an_array[:5]
print(first_five)
five_to_end = an_array[5:]
print(five_to_end)

[0 1 2 3 4]
[ 5  6  7  8  9 10]


Stride Length

In [24]:
# Stride by two
stride_by_to = an_array[5::2]
print(stride_by_to)

[5 7 9]


In [28]:
first_five_reversed = an_array[4::-1]
print(first_five_reversed)

[4 3 2 1 0]


In [29]:
final_two = an_array[-2:]
print(final_two)

[ 9 10]


In [31]:
# get length
print(an_array.size)

11


In [32]:
# get max value in array
print(np.amax(an_array))

10


In [ ]:
# get min val in array