Create Matrices in Numpy

In [1]:
import numpy as np

In [6]:
# 2 x 2 Matrix
two_by_two = np.matrix([[1, 2], [3, 4]])
print(two_by_two)

[[1 2]
 [3 4]]


In [10]:
two_by_three = np.matrix([[1,2],[3, 4], [5, 6]])
print(type(two_by_three))
print(two_by_three)

<class 'numpy.matrix'>
[[1 2]
 [3 4]
 [5 6]]


In [12]:
two_by_four = np.matrix('1, 2; 3, 4; 5, 6; 7, 8')
print(two_by_four)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


* Make zeros or ones matrices
    * np.zeros(rows, cols)

In [20]:
np.ones([2, 3]) # 2 rows, 3 columns

array([[1., 1., 1.],
       [1., 1., 1.]])

In [23]:
np.zeros([5, 6]) # 5 rows, 6 columns

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])