Go over a quick example of matrices in action

In [1]:
import numpy as np

In [4]:
image_matrix = np.matrix('0 0 1 0 0; 0 0 1 0 0; 0 0 1 0 0; 0 0 1 0 0; 0 0 1 0 0')
print(image_matrix)

[[0 0 1 0 0]
 [0 0 1 0 0]
 [0 0 1 0 0]
 [0 0 1 0 0]
 [0 0 1 0 0]]


In [7]:
image_matrix[2] = [1, 1, 1, 1, 1]
print(image_matrix)

[[0 0 1 0 0]
 [0 0 1 0 0]
 [1 1 1 1 1]
 [0 0 1 0 0]
 [0 0 1 0 0]]


In [10]:
rows = image_matrix.shape[0]
columns = image_matrix.shape[1]
print(f"Rows: {rows}")
print(f"Columns: {columns}")

Rows: 5
Columns: 5


In [13]:
for row in range(rows):
    for column in range(columns):
        if image_matrix[row, column] == 0:
            image_matrix[row, column] = 1
        else:
            image_matrix[row, column] = 0
print(image_matrix)

[[1 1 0 1 1]
 [1 1 0 1 1]
 [0 0 0 0 0]
 [1 1 0 1 1]
 [1 1 0 1 1]]


In [14]:
image_matrix[2] = [1, 1, 0, 1, 1]

In [15]:
print(image_matrix)

[[1 1 0 1 1]
 [1 1 0 1 1]
 [1 1 0 1 1]
 [1 1 0 1 1]
 [1 1 0 1 1]]


In [16]:
print(image_matrix.T)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [0 0 0 0 0]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [17]:
print(image_matrix.flatten())

[[1 1 0 1 1 1 1 0 1 1 1 1 0 1 1 1 1 0 1 1 1 1 0 1 1]]
