Functions to get elements or properties of metrices

In [1]:
import numpy as np

In [3]:
a_matrix = np.matrix('1, 2, 3; 4, 5, 6; 7, 8, 9')
print(a_matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
a_matrix[0]

matrix([[1, 2, 3]])

In [7]:
# fetch data specified
a_matrix[1, 0] # first parameter is index of arrays, second parameter is items for sub arrays

4

In [10]:
a_matrix[2, 2]

9

In [13]:
print(a_matrix[2, 1:])

[[8 9]]


In [17]:
# Get size of the matrix
a_matrix.size

9

In [19]:
# Get shape of the matrix
a_matrix.shape

(3, 3)

In [27]:
np.amax(a_matrix)

9

In [28]:
np.amin(a_matrix)

1

In [29]:
np.average(a_matrix)

5.0

In [30]:
# Using method

In [32]:
a_matrix.max()

9

In [33]:
a_matrix.min()

1

In [35]:
a_matrix.mean()

5.0