Operations to modify numpy array or the elements within

In [1]:
import numpy as np

In [2]:
an_array = np.arange(0, 6)
print(an_array)

[0 1 2 3 4 5]


In [4]:
an_array[0] = 10
print(an_array)

[10  1  2  3  4  5]


In [6]:
an_array = np.arange(0, 6)

In [8]:
# Append, add new data in the end of array
np.append(an_array, 6)

array([0, 1, 2, 3, 4, 5, 6])

In [10]:
np.append(an_array, [6, 7, 8, 9])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
# Insert, based on start point index
print(np.insert(an_array, 0, [10, 11]))
print(np.insert(an_array, 1, [10, 11]))
print(np.insert(an_array, 2, [10, 11]))

[10 11  0  1  2  3  4  5]
[ 0 10 11  1  2  3  4  5]
[ 0  1 10 11  2  3  4  5]


In [20]:
# delete
print(f"Before deleting: {an_array}")
print(f"After deleting third index: {np.delete(an_array, 3)}")

Before deleting: [0 1 2 3 4 5]
After deleting third index: [0 1 2 4 5]


In [23]:
# Array Operation
print(f"Multiply all of elements by 2: {an_array * 2}")
print(f"We also can peform addition: {an_array + 2}")

Multiply all of elements by 2: [ 0  2  4  6  8 10]
We also can peform addition: [2 3 4 5 6 7]


In [38]:
# Sorting
another_array = np.array([3, 6, 21, 9, 10, 1])
print(f"Before sorting the data: {another_array}")
print(f"After sorting the data: {np.sort(another_array)}")

Before sorting the data: [ 3  6 21  9 10  1]
After sorting the data: [ 1  3  6  9 10 21]


In [39]:
print(f"Covert all of data to negative and sort them: {-np.sort(another_array)}")
print(f"Descending order with negative value: {np.sort(-another_array)}")
print(f"Descending order with positive value: {-np.sort(-another_array)}")

Covert all of data to negative and sort them: [ -1  -3  -6  -9 -10 -21]
Descending order with negative value: [-21 -10  -9  -6  -3  -1]
Descending order with positive value: [21 10  9  6  3  1]
