Function to modify elements or properties of a matrix

In [1]:
import numpy as np

In [6]:
a_matrix = np.matrix('1 2; 3 4')
a_matrix

matrix([[1, 2],
        [3, 4]])

In [10]:
# Update value
print(a_matrix[1, 0])
a_matrix[1, 0] = 10
print(a_matrix)

10
[[ 1  2]
 [10  4]]


In [12]:
print(a_matrix[0])
a_matrix[0] = [6, 3]
print(a_matrix)

[[6 3]]
[[ 6  3]
 [10  4]]


In [14]:
print(np.sort(a_matrix))

[[ 3  6]
 [ 4 10]]


In [16]:
print(-np.sort(-a_matrix))

[[ 6  3]
 [10  4]]


In [46]:
a_matrix = np.matrix('1 2; 3, 4')
print(a_matrix)
print(a_matrix.T) # .T is for transpose

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


In [47]:
# Flatten Operation

In [48]:
print(a_matrix.flatten()) # make matrix to one row

[[1 2 3 4]]


In [49]:
print(a_matrix + 1) # Add all values w/ 1

[[2 3]
 [4 5]]


In [50]:
# Sum two matrix
print(np.add(a_matrix, a_matrix))

[[2 4]
 [6 8]]


In [54]:
# Multiply
print(np.matmul(a_matrix, a_matrix))

[[ 7 10]
 [15 22]]
